sudo: required
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libboost-python-dev libboost-all-dev systemtap-sdt-dev libfuzzy-dev graphviz
  - git clone https://github.com/buffer/libemu.git
  - cd libemu
  - autoreconf -v -i
  - ./configure
  - sudo make install
  - cd -
  - sudo ldconfig
install:
  - sudo pip install pylibemu
  - pip install tox
script:
  - sudo mkdir -p /etc/thug/{rules,personalities,scripts}
  - sudo cp -R thug/Classifier/rules/* /etc/thug/rules/
  - sudo cp -R thug/DOM/personalities/* /etc/thug/personalities
  - sudo cp -t /etc/thug/scripts thug/DOM/{thug.js,storage.js,date.js,eval.js,write.js} thug/Debugger/d8.js
  - sudo cp -t /etc/thug/ conf/thug.conf
  - tox
  - echo "Build done"
